import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import CountryDisplay from "../src/country-display";
import SearchBar from "../src/searchBar";
import styles from "../styles/Home.module.css";

interface IndexPageProps {
  data: {
    [x: string]: any;
    name: string;
    capital: string;
    flag: string;
    population: number;
    region: string;
    independent: boolean;
  };
}

const Home: NextPage<IndexPageProps> = ({ data }) => {
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Countries Display</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <div>Where in the world?</div>
      </header>

      <div className={styles.bodyContainer}>
        <SearchBar></SearchBar>

        <div className="country-display-container">
          {data.map((data: any) => {
            return (
              <CountryDisplay
                key={data.name}
                name={data.name}
                population={data.population}
                region={data.region}
                capital={data.capital}
                flag={data.flag}
              />
            );
          })}
        </div>
        {/* <CountryDisplay
          name={"Germany"}
          population={81770900}
          region={"Europe"}
          capital={"Berlin"}
          flag={"https://flagcdn.com/de.svg"}
        /> */}
      </div>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  // console.log("fetching data");
  const res = await fetch(
    "https://restcountries.com/v2/all?fields=name,capital,population,region,flag"
  );
  // const res = await fetch("https://picsum.photos/v2/list?page=2&limit=100");
  const data = await res.json();
  // console.log("printing data!");
  // console.log(data);

  // Pass data to the page via props
  return {
    props: {
      data,
    },
  };
};

export default Home;
