import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import CountryDisplay from "../src/country-display";
import SearchBar from "../src/searchBar";
import styles from "../styles/Home.module.css";

interface IndexPageProps {
  data: {
    [x: string]: any;
    name: string;
    capital: string;
    flags: [];
    population: number;
    region: string;
    independent: boolean;
    currencies: [];
    languages: [];
  };
}

interface SelectedCountry {
  name: string;
}

const Home: NextPage<IndexPageProps> = ({ data }) => {
  const [curData, setCurData] = useState<SelectedCountry>({ name: "" });

  return (
    <div className={styles.container}>
      <Head>
        <title>Countries Display</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <div>Where in the world?</div>
      </header>

      <div className={styles.bodyContainer}>
        <SearchBar></SearchBar>

        <div className={styles.countryDisplayContainer}>
          {data.map((data: any) => {
            return (
              <CountryDisplay
                key={data.name["common"]}
                name={data.name["common"]}
                population={data.population}
                region={data.region}
                capital={data.capital}
                flag={data.flags["svg"]}
              />
            );
          })}
        </div>

        <CountryDisplay
          name={"Germany"}
          population={81770900}
          region={"Europe"}
          capital={"Berlin"}
          flag={data[0].flags["svg"]}
        />
      </div>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  // console.log("fetching data");
  const res = await fetch(
    "https://restcountries.com/v3.1/all?fields=name,capital,population,region,subregion,flags,independent,currencies,languages,borders"
  );
  // const res = await fetch("https://picsum.photos/v2/list?page=2&limit=100");
  const data = await res.json();
  // console.log("printing data!");
  // console.log(data);

  // Pass data to the page via props
  return {
    props: {
      data,
    },
  };
};

export default Home;
